//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinFormsClient.ServiceDBMS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceDBMS.IServiceDBMS")]
    public interface IServiceDBMS {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDBMS/CreateDB", ReplyAction="http://tempuri.org/IServiceDBMS/CreateDBResponse")]
        bool CreateDB(string dbname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDBMS/AddTable", ReplyAction="http://tempuri.org/IServiceDBMS/AddTableResponse")]
        bool AddTable(string tname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDBMS/GetListCNames", ReplyAction="http://tempuri.org/IServiceDBMS/GetListCNamesResponse")]
        string[] GetListCNames(int index);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDBMS/GetListCTypes", ReplyAction="http://tempuri.org/IServiceDBMS/GetListCTypesResponse")]
        string[] GetListCTypes(int index);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDBMS/GetListRows", ReplyAction="http://tempuri.org/IServiceDBMS/GetListRowsResponse")]
        string[][] GetListRows(int index);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDBMS/AddColumn", ReplyAction="http://tempuri.org/IServiceDBMS/AddColumnResponse")]
        bool AddColumn(int tIndex, string cname, string ctype, string interval);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDBMS/AddRow", ReplyAction="http://tempuri.org/IServiceDBMS/AddRowResponse")]
        bool AddRow(int tIndex);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDBMS/ChangeValue", ReplyAction="http://tempuri.org/IServiceDBMS/ChangeValueResponse")]
        bool ChangeValue(string newValue, int tind, int cind, int rind);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDBMS/DeleteRow", ReplyAction="http://tempuri.org/IServiceDBMS/DeleteRowResponse")]
        void DeleteRow(int tind, int rind);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDBMS/DeleteColumn", ReplyAction="http://tempuri.org/IServiceDBMS/DeleteColumnResponse")]
        void DeleteColumn(int tind, int cind);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDBMS/DeleteTable", ReplyAction="http://tempuri.org/IServiceDBMS/DeleteTableResponse")]
        void DeleteTable(int tind);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDBMS/SaveDB", ReplyAction="http://tempuri.org/IServiceDBMS/SaveDBResponse")]
        void SaveDB(string path);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDBMS/OpenDB", ReplyAction="http://tempuri.org/IServiceDBMS/OpenDBResponse")]
        void OpenDB(string path);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDBMS/GetTableNameList", ReplyAction="http://tempuri.org/IServiceDBMS/GetTableNameListResponse")]
        string[] GetTableNameList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDBMS/GetDBName", ReplyAction="http://tempuri.org/IServiceDBMS/GetDBNameResponse")]
        string GetDBName();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDBMS/JoinTables", ReplyAction="http://tempuri.org/IServiceDBMS/JoinTablesResponse")]
        bool JoinTables(string t1name, string t2name);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceDBMSChannel : WinFormsClient.ServiceDBMS.IServiceDBMS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceDBMSClient : System.ServiceModel.ClientBase<WinFormsClient.ServiceDBMS.IServiceDBMS>, WinFormsClient.ServiceDBMS.IServiceDBMS {
        
        public ServiceDBMSClient() {
        }
        
        public ServiceDBMSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceDBMSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceDBMSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceDBMSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool CreateDB(string dbname) {
            return base.Channel.CreateDB(dbname);
        }
        
        public bool AddTable(string tname) {
            return base.Channel.AddTable(tname);
        }
        
        public string[] GetListCNames(int index) {
            return base.Channel.GetListCNames(index);
        }
        
        public string[] GetListCTypes(int index) {
            return base.Channel.GetListCTypes(index);
        }
        
        public string[][] GetListRows(int index) {
            return base.Channel.GetListRows(index);
        }
        
        public bool AddColumn(int tIndex, string cname, string ctype, string interval) {
            return base.Channel.AddColumn(tIndex, cname, ctype, interval);
        }
        
        public bool AddRow(int tIndex) {
            return base.Channel.AddRow(tIndex);
        }
        
        public bool ChangeValue(string newValue, int tind, int cind, int rind) {
            return base.Channel.ChangeValue(newValue, tind, cind, rind);
        }
        
        public void DeleteRow(int tind, int rind) {
            base.Channel.DeleteRow(tind, rind);
        }
        
        public void DeleteColumn(int tind, int cind) {
            base.Channel.DeleteColumn(tind, cind);
        }
        
        public void DeleteTable(int tind) {
            base.Channel.DeleteTable(tind);
        }
        
        public void SaveDB(string path) {
            base.Channel.SaveDB(path);
        }
        
        public void OpenDB(string path) {
            base.Channel.OpenDB(path);
        }
        
        public string[] GetTableNameList() {
            return base.Channel.GetTableNameList();
        }
        
        public string GetDBName() {
            return base.Channel.GetDBName();
        }
        
        public bool JoinTables(string t1name, string t2name) {
            return base.Channel.JoinTables(t1name, t2name);
        }
    }
}
